# Generated by Django 4.0.2 on 2024-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
